<?php
/**
 * @file
 * Provide placement information from the IMS service.
 */

/**
 * Implements hook_menu().
 */
function ims_menu() {
  $items = array();

  $items['admin/config/ding/provider/ims'] = array(
    'title' => 'IMS provider',
    'description' => 'Settings for the IMS service.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ims_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'ims.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_ding_provider().
 */
function ims_ding_provider() {
  return array(
    'title' => 'IMS: Ding provider',
    'provides' => array(
      'availability' => array(
        'prefix' => 'availability',
        'file' => 'includes/ims.availability.inc',
      ),
    ),
  );
}

/**
 * Fetch placement information from IMS service.
 * 
 * @param array $provider_ids
 *   Array of ting object ids (faust).
 *
 * @return array
 *   Placements info.
 */
function ims_placements($provider_ids) {
  
  // @todo Call the IMS Webservice. 
  /*
  try {
    $service = new ImsService(variable_get('ims_wsdl_url'), variable_get('ims_username'), variable_get('ims_password'));

    // Retrieve covers by PID.
    $retrieved = $service->getByFaustNumber($provider_ids);
  }
  catch (Exception $e) {
    watchdog('ting_covers_ims', 'Unable to retrieve placements from IMS: %message', array('%message' => $e->getMessage()), WATCHDOG_ERROR);

    // Error in fetching, return no covers.
    return array();
  }
  */
  

  // @todo Remove example 
  // This is an example of what could be returned by the webservice.
  // Faust 52673542 - Kvinderne fra Thy. 
  // We pretend that two of 30 matrials are on display

  
  $retrieved = array(
    "52673542" => array(
      "5133663391" => array(
          0 => "Biblioteket Sønderborg",
          1 => "Niveau 2",
          2 => "Voksenbibliotek",
          3 => "Gallerivæggen ved fiktion"
      ),
      "5131171783" => array(
        0 => "Biblioteket Sønderborg",
        1 => "Niveau 2",
        2 => "Voksenbibliotek",
        3 => "Gallerivæggen ved fiktion"
    ),
    )
  );
 
  return $retrieved;
}