<?php

/**
 * @file
 * Provide placement information from the IMS service.
 */

/**
 * Implements hook_menu().
 */
function ims_menu() {
  $items = array();

  $items['admin/config/ding/provider/ims'] = array(
    'title' => 'IMS provider',
    'description' => 'Settings for the IMS service.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ims_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'ims.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_ding_provider().
 */
function ims_ding_provider() {
  return array(
    'title' => 'IMS: Ding provider',
    'provides' => array(
      'availability' => array(
        'prefix' => 'availability',
        'file' => 'inc/ims.availability.inc',
      ),
    ),
  );
}

/**
 * Fetch placement information from IMS service.
 *
 * @param array $provider_ids
 *   Array of ting object ids (faust).
 *
 * @return array
 *   Placements info.
 */
function ims_placements(array $provider_ids) {
  // Call the IMS Webservice.
  try {
    $service = new ImsService(variable_get('ims_wsdl_url'), variable_get('ims_username'), variable_get('ims_password'));

    // Retrieve placements for multiple ting object ids.
    $retrieved = $service->getByFaustNumber($provider_ids);
  }
  catch (ImsException $e) {
    // Re-throw Ims specific exception.
    throw new ImsServiceException($e->getMessage());
  }
  return $retrieved;
}
